In [3]:
import numpy as np

In [25]:
#Matrik 1D
mat1D = np.array([1,2,3,4,5,6,7,8,9,10,])
mat2D = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [13]:
print(mat1D)

[ 1  2  3  4  5  6  7  8  9 10]


In [17]:
print(mat1D[0])

1


In [19]:
print(mat1D + 5)

[ 6  7  8  9 10 11 12 13 14 15]


In [30]:
print(mat2D)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [40]:
print(mat2D[0])
print(mat2D[1])
print(mat2D[2])

[1 2 3]
[4 5 6]
[7 8 9]


In [42]:
print(mat2D[0][2])

3


In [46]:
print(mat2D * [10])

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [54]:
print(mat1D.shape)
print(mat2D.shape)

(10,)
(3, 3)


In [58]:
print(mat1D.size)
print(mat2D.size)

10
9


In [92]:
#Special Matrix
mZero = np.zeros((3,3))
mIdentity = np.eye((4))
mFull = np.full((4,4),7)
mOne = np.ones((5,4))
mRandomFloat = np.random.rand(5,5)
mRandomInt = np.random.randint(10,101, size=6)

In [94]:
print(mZero)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [96]:
print(mIdentity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [98]:
print(mOne)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [100]:
print(mRandomFloat)

[[0.03490731 0.93719759 0.6558954  0.47472141 0.27507813]
 [0.72684079 0.01304729 0.1982115  0.30596881 0.1075603 ]
 [0.42905381 0.59655616 0.14830719 0.1394716  0.92458805]
 [0.49934479 0.89975231 0.19829495 0.43324848 0.1800268 ]
 [0.887491   0.81110113 0.11797823 0.17250341 0.59567498]]


In [104]:
print(mRandomInt)

[24 74 65 21 81 20]


In [122]:
x = np.array([2,6,9,5,6,3])
y = np.array([2,6,1,7,3,4])

dotProduct = np.dot(x,y)
addMatrix = np.add(x,y)
minValue = np.min(x)
maxValue = np.max(y)
meanValue = np. mean(y)
medianValue = np.median(y)
stdValue = np.std(y)

print(f"Hasil dari dot Product : {dotProduct}")
print(f"Hasil penjumlahan matrix : {addMatrix}")
print(f"nilai minimum dari {x}: {minValue}")
print(f"Nilai Maksimum dari {y}: {maxValue}")
print(f"Rata Rata Nilai dari {y} : {meanValue}")
print(f"nilai median dari {y} : {medianValue}")
print(f"Nilai Deviasi Dari {y} : {stdValue}")

Hasil dari dot Product : 114
Hasil penjumlahan matrix : [ 4 12 10 12  9  7]
nilai minimum dari [2 6 9 5 6 3]: 2
Nilai Maksimum dari [2 6 1 7 3 4]: 7
Rata Rata Nilai dari [2 6 1 7 3 4] : 3.8333333333333335
nilai median dari [2 6 1 7 3 4] : 3.5
Nilai Deviasi Dari [2 6 1 7 3 4] : 2.1147629234082532


In [130]:
myArray = np.array([[1,2,3],[4,5,6]])

reshape = myArray.reshape(3,2)
flatten = myArray.flatten()

print(reshape)
print(flatten)

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [138]:
#Filtering
nilaiSiswa = np.array([80,90,60,50,50,100,95])
Lulus = nilaiSiswa[nilaiSiswa > 50]
jumlah = Lulus.size
print(Lulus)
print(f"jumlah siswa yang lulus:{jumlah}")

[ 80  90  60 100  95]
jumlah siswa yang lulus:5
